# Generated by Django 3.2.6 on 2021-08-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0002_auto_20210809_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='year',
            field=models.CharField(choices=[('None', 'None'), ('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('forth', 'Forth')], default='None', max_length=255),
        ),
    ]
