# Generated by Django 3.2.6 on 2021-08-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0004_auto_20210809_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classrecord',
            options={'verbose_name': 'Class Record', 'verbose_name_plural': 'Class Record'},
        ),
        migrations.AlterModelOptions(
            name='collegerecord',
            options={'verbose_name': 'College Record', 'verbose_name_plural': 'College Record'},
        ),
        migrations.AlterModelOptions(
            name='studentrecord',
            options={'verbose_name': 'Student Record', 'verbose_name_plural': 'Student Record'},
        ),
        migrations.AlterModelTable(
            name='classrecord',
            table='classrecord',
        ),
        migrations.AlterModelTable(
            name='collegerecord',
            table='collegerecord',
        ),
        migrations.AlterModelTable(
            name='studentrecord',
            table='studentrecord',
        ),
    ]
