# Generated by Django 3.2.6 on 2021-08-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0006_alter_classrecord_collegename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecord',
            name='collegename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collegerecord_set', to='modelform.collegerecord'),
        ),
    ]
