# Generated by Django 3.2.6 on 2021-08-14 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0007_alter_classrecord_collegename'),
    ]

    operations = [
       # migrations.AlterModelOptions(
       #     name='classrecord',
       #     options={},
       # ),
       # migrations.AlterModelOptions(
       #     name='collegerecord',
       #     options={},
       # ),
       # migrations.AlterModelOptions(
       #     name='studentrecord',
       #     options={},
       # ),
        migrations.AlterField(
            model_name='classrecord',
            name='collegename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collegename', to='modelform.collegerecord'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='classname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classname', to='modelform.classrecord'),
        ),
        #migrations.AlterModelTable(
        #    name='classrecord',
        #    table=None,
        #),
        #migrations.AlterModelTable(
        #    name='collegerecord',
        #    table=None,
        #),
        #migrations.AlterModelTable(
        #    name='studentrecord',
        #    table=None,
        #),
    ]
