# Generated by Django 3.2.6 on 2021-08-16 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modelform', '0008_auto_20210814_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classrecord',
            options={'verbose_name': 'Class Record', 'verbose_name_plural': 'Class Record'},
        ),
        migrations.AlterModelOptions(
            name='collegerecord',
            options={'verbose_name': 'College Record', 'verbose_name_plural': 'College Record'},
        ),
        migrations.AlterModelOptions(
            name='studentrecord',
            options={'verbose_name': 'Student Record', 'verbose_name_plural': 'Student Record'},
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
