# Generated by Django 3.2.6 on 2021-09-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0009_auto_20210816_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegerecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
